#!/bin/bash
fifo=$(mktemp -u)
mkfifo "$fifo"

cat > "$fifo" &
cat_pid=$!

IPFS_COVERT_RET_FILE=$(mktemp)
export IPFS_COVERT_RET_FILE
if test -z "$COVER_FMT"; then
	echo "Needs to set COVER_FMT=$COVER_FMT"
	exit 1
fi

_term() {
	kill -TERM "$child_pid" 2>/dev/null
	kill "$cat_pid" 2>/dev/null
}
trap _term SIGTERM

tail -f --pid="$cat_pid" "$fifo" -s 0.005 | ipfs-test-cover -test.run "^TestRunMain$" -test.coverprofile="$(mktemp "$COVER_FMT")" -- "$@" &

child_pid=$!

wait "$child_pid"
kill "$cat_pid" 2>/dev/null

ECODE=$(cat "$IPFS_COVERT_RET_FILE")
rm -f "$IPFS_COVERT_RET_FILE"

exit "$ECODE"
